=== chendz/SuperMinijoe/src/uk/org/freedonia/jfreewhois/etc/sample.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Copyright (c) 2013 Joe Beeton.
  All rights reserved. This program and the accompanying materials
  are made available under the terms of the GNU Lesser Public License v2.1
  which accompanies this distribution, and is available at
  http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
  
  Contributors:
      Joe Beeton - initial API and implementation
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="WhoisServerList">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="WhoisServerDefinition"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="WhoisServerDefinition">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="address"/>
        <xs:element maxOccurs="unbounded" ref="tld"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="name" type="xs:NCName"/>
  <xs:element name="address" type="xs:NCName"/>
  <xs:element name="tld" type="xs:NCName"/>
</xs:schema>

=== chendz/SuperMinijoe/src/uk/org/freedonia/jfreewhois/etc/serverlist.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--
  Copyright (c) 2013 Joe Beeton.
  All rights reserved. This program and the accompanying materials
  are made available under the terms of the GNU Lesser Public License v2.1
  which accompanies this distribution, and is available at
  http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
  
  Contributors:
      Joe Beeton - initial API and implementation
-->
<WhoisServerList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="sample.xsd">
  
  
  <WhoisServerDefinition>
    <name>whois.crsnic.net</name>
    <address>whois.crsnic.net</address>
    <tld>com</tld>
    <tld>net</tld>
  </WhoisServerDefinition>
  
  <WhoisServerDefinition>
    <name>whois.pir.org</name>
    <address>whois.pir.org</address>
    <tld>org</tld>
  </WhoisServerDefinition>
  
  <WhoisServerDefinition>
    <name>whois.publicinterestregistry.net</name>
    <address>whois.publicinterestregistry.net</address>
    <tld>org</tld>
  </WhoisServerDefinition>
  
  <WhoisServerDefinition>
    <name>whois.afilias.info</name>
    <address>whois.afilias.info</address>
    <tld>info</tld>
  </WhoisServerDefinition>
  
  <WhoisServerDefinition>
    <name>whois.afilias.net</name>
    <address>whois.afilias.net</address>
    <tld>info</tld>
  </WhoisServerDefinition>
  
  <WhoisServerDefinition>
    <name>whois.neulevel.biz</name>
    <address>whois.neulevel.biz</address>
    <tld>biz</tld>
  </WhoisServerDefinition>
  
  <WhoisServerDefinition>
    <name>whois.nic.us</name>
    <address>whois.nic.us</address>
    <tld>us</tld>
  </WhoisServerDefinition>
  
  <WhoisServerDefinition>
    <name>whois.nic.uk</name>
    <address>whois.nic.uk</address>
    <tld>uk</tld>
    <tld>co.uk</tld>
    <tld>org.uk</tld>
    <tld>ltd.uk</tld>
  </WhoisServerDefinition>
  
  <WhoisServerDefinition>
    <name>whois.cira.ca</name>
    <address>whois.cira.ca</address>
    <tld>ca</tld>
    <tld>ab.ca</tld>
    <tld>bc.ca</tld>
    <tld>mb.ca</tld>
    <tld>nb.ca</tld>
    <tld>nf.ca</tld>
    <tld>nl.ca</tld>
    <tld>ns.ca</tld>
    <tld>nt.ca</tld>
    <tld>nu.ca</tld>
    <tld>on.ca</tld>
    <tld>pe.ca</tld>
    <tld>qc.ca</tld>
    <tld>sk.ca</tld>
   	<tld>yk.ca</tld>
  </WhoisServerDefinition>
  
  <WhoisServerDefinition>
    <name>whois.nic.tel</name>
    <address>whois.nic.tel</address>
    <tld>tel</tld>
  </WhoisServerDefinition>
  
  <WhoisServerDefinition>
    <name>whois.iedr.ie</name>
    <address>whois.iedr.ie</address>
    <tld>ie</tld>
  </WhoisServerDefinition>
  
  <WhoisServerDefinition>
    <name>whois.domainregistry.ie</name>
    <address>whois.domainregistry.ie</address>
    <tld>ie</tld>
  </WhoisServerDefinition>
  
  <WhoisServerDefinition>
    <name>whois.nic.it</name>
    <address>whois.nic.it</address>
    <tld>it</tld>
  </WhoisServerDefinition>
  
  <WhoisServerDefinition>
    <name>whois.nic.li</name>
    <address>whois.nic.li</address>
    <tld>li</tld>
  </WhoisServerDefinition>
  
  <WhoisServerDefinition>
    <name>whois.norid.no</name>
    <address>whois.norid.no</address>
    <tld>no</tld>
  </WhoisServerDefinition>
  
  <WhoisServerDefinition>
    <name>whois.nic.cc</name>
    <address>whois.nic.cc</address>
    <tld>cc</tld>
  </WhoisServerDefinition>
  
  <WhoisServerDefinition>
    <name>whois.eu</name>
    <address>whois.eu</address>
    <tld>eu</tld>
  </WhoisServerDefinition>
  
  <WhoisServerDefinition>
    <name>whois.nic.nu</name>
    <address>whois.nic.nu</address>
    <tld>nu</tld>
  </WhoisServerDefinition>
  
  <WhoisServerDefinition>
    <name>whois.aunic.net</name>
    <address>whois.aunic.net</address>
    <tld>au</tld>
    <tld>net.au</tld>
    <tld>com.au</tld>
    <tld>org.au</tld>
  </WhoisServerDefinition>
  
  <WhoisServerDefinition>
    <name>whois.ausregistry.net.au</name>
    <address>whois.ausregistry.net.au</address>
    <tld>au</tld>
  </WhoisServerDefinition>
  
  <WhoisServerDefinition>
    <name>whois.denic.de</name>
    <address>whois.denic.de</address>
    <tld>de</tld>
  </WhoisServerDefinition>
  
  <WhoisServerDefinition>
    <name>whois.worldsite.ws</name>
    <address>whois.worldsite.ws</address>
    <tld>wd</tld>
  </WhoisServerDefinition>
  
  <WhoisServerDefinition>
    <name>whois.nic.ws</name>
    <address>whois.nic.ws</address>
    <tld>ws</tld>
  </WhoisServerDefinition>
  
  <WhoisServerDefinition>
    <name>www.nic.ws</name>
    <address>www.nic.ws</address>
    <tld>ws</tld>
  </WhoisServerDefinition>
  
  <WhoisServerDefinition>
    <name>whois2.afilias-grs.net</name>
    <address>whois2.afilias-grs.net</address>
    <tld>sc</tld>
    <tld>hn</tld>
    <tld>la</tld>
    <tld>vc</tld>
  </WhoisServerDefinition>
  
  <WhoisServerDefinition>
    <name>whois.dotmobiregistry.net</name>
    <address>whois.dotmobiregistry.net</address>
    <tld>mobi</tld>
  </WhoisServerDefinition>
  
  <WhoisServerDefinition>
    <name>whois.registrypro.pro</name>
    <address>whois.registrypro.pro</address>
    <tld>pro</tld>
  </WhoisServerDefinition>
  
  <WhoisServerDefinition>
    <name>whois.registry.pro</name>
    <address>whois.registry.pro</address>
    <tld>pro</tld>
    <tld>aaa.pro</tld>
    <tld>aca.pro</tld>
    <tld>acct.pro</tld>
    <tld>arc.pro</tld>
    <tld>avocat.pro</tld>
    <tld>bar.pro</tld>
    <tld>bus.pro</tld>
    <tld>cfp.pro</tld>
    <tld>chi.pro</tld>
    <tld>chiro.pro</tld>
    <tld>cpa.pro</tld>
    <tld>dds.pro</tld>
    <tld>den.pro</tld>
    <tld>dent.pro</tld>
    <tld>ed.pro</tld>
    <tld>eng.pro</tld>
    <tld>jur.pro</tld>
    <tld>law.pro</tld>
    <tld>med.pro</tld>
    <tld>min.pro</tld>
    <tld>ntr.pro</tld>
    <tld>nur.pro</tld>
    <tld>nurse.pro</tld>
    <tld>opt.pro</tld>
    <tld>pa.pro</tld>
    <tld>pha.pro</tld>
    <tld>pharma.pro</tld>
    <tld>pod.pro</tld>
    <tld>pr.pro</tld>
    <tld>prof.pro</tld>
    <tld>prx.pro</tld>
    <tld>psy.pro</tld>
    <tld>pt.pro</tld>
    <tld>recht.pro</tld>
    <tld>rel.pro</tld>
    <tld>teach.pro</tld>
    <tld>vet.pro</tld>
  </WhoisServerDefinition>
  
  <WhoisServerDefinition>
    <name>whois.educause.net</name>
    <address>whois.educause.net</address>
    <tld>edu</tld>
  </WhoisServerDefinition>
  
  <WhoisServerDefinition>
    <name>whois.crsnic.net</name>
    <address>whois.crsnic.net</address>
    <tld>edu</tld>
  </WhoisServerDefinition>
  
  <WhoisServerDefinition>
    <name>whois.nic.tv</name>
    <address>whois.nic.tv</address>
    <tld>tv</tld>
  </WhoisServerDefinition>
  
  <WhoisServerDefinition>
    <name>tvwhois.verisign-grs.com</name>
    <address>tvwhois.verisign-grs.com</address>
    <tld>tv</tld>
  </WhoisServerDefinition>
  
  <WhoisServerDefinition>
    <name>whois.nic.travel</name>
    <address>whois.nic.travel</address>
    <tld>travel</tld>
  </WhoisServerDefinition>
  
  <WhoisServerDefinition>
    <name>whois.nic.name</name>
    <address>whois.nic.name</address>
    <tld>name</tld>
  </WhoisServerDefinition>
  
  <WhoisServerDefinition>
    <name>whois.registry.in</name>
    <address>whois.registry.in</address>
    <tld>in</tld>
  </WhoisServerDefinition>
  
  <WhoisServerDefinition>
    <name>whois.inregistry.net</name>
    <address>whois.inregistry.net</address>
    <tld>in</tld>
    <tld>co.in</tld>
    <tld>net.in</tld>
    <tld>org.in</tld>
    <tld>firm.in</tld>
    <tld>gen.in</tld>
    <tld>ind.in</tld>
  </WhoisServerDefinition>
  
  <WhoisServerDefinition>
    <name>whois.nic.me</name>
    <address>whois.nic.me</address>
    <tld>me</tld>
  </WhoisServerDefinition>
  
  <WhoisServerDefinition>
    <name>whois.meregistry.net</name>
    <address>whois.meregistry.net</address>
    <tld>me</tld>
  </WhoisServerDefinition>
  
 <WhoisServerDefinition>
    <name>whois.nic.at</name>
    <address>whois.nic.at</address>
    <tld>at</tld>
    <tld>co.at</tld>
    <tld>or.at</tld>
  </WhoisServerDefinition> 
  
  <WhoisServerDefinition>
    <name>whois.dns.be</name>
    <address>whois.dns.be</address>
    <tld>be</tld>
  </WhoisServerDefinition>
  
  <WhoisServerDefinition>
    <name>whois.cnnic.cn</name>
    <address>whois.cnnic.cn</address>
    <tld>cn</tld>
    <tld>ah.cn</tld>
    <tld>bj.cn</tld>
    <tld>com.cn</tld>
    <tld>cq.cn</tld>
    <tld>fj.cn</tld>
    <tld>gd.cn</tld>
    <tld>gs.cn</tld>
    <tld>gx.cn</tld>
    <tld>gz.cn</tld>
    <tld>ha.cn</tld>
    <tld>hb.cn</tld>
    <tld>he.cn</tld>
    <tld>hi.cn</tld>
    <tld>hk.cn</tld>
    <tld>hl.cn</tld>
    <tld>hn.cn</tld>
    <tld>jl.cn</tld>
    <tld>js.cn</tld>
    <tld>jx.cn</tld>
    <tld>ln.cn</tld>
    <tld>mo.cn</tld>
    <tld>net.cn</tld>
    <tld>nm.cn</tld>
    <tld>nx.cn</tld>
    <tld>org.cn</tld>
    <tld>qh.cn</tld>
    <tld>sc.cn</tld>
    <tld>sd.cn</tld>
    <tld>sh.cn</tld>
    <tld>sn.cn</tld>
    <tld>sx.cn</tld>
    <tld>tj.cn</tld>
    <tld>tw.cn</tld>
    <tld>xj.cn</tld>
  </WhoisServerDefinition>
  
  <WhoisServerDefinition>
    <name>whois.cnnic.net.cn</name>
    <address>whois.cnnic.net.cn</address>
    <tld>cn</tld>
  </WhoisServerDefinition>
  
  <WhoisServerDefinition>
    <name>whois.nic.asia</name>
    <address>whois.nic.asia</address>
    <tld>asia</tld>
  </WhoisServerDefinition>
  
  <WhoisServerDefinition>
    <name>whois.ripn.ru</name>
    <address>whois.ripn.ru</address>
    <tld>ru</tld>
  </WhoisServerDefinition>
  
  <WhoisServerDefinition>
    <name>whois.ripn.net</name>
    <address>whois.ripn.net</address>
    <tld>com.ru</tld>
    <tld>int.ru</tld>
    <tld>net.ru</tld>
    <tld>org.ru</tld>
    <tld>pp.ru</tld>
    <tld>su</tld>
  </WhoisServerDefinition>
  
  <WhoisServerDefinition>
    <name>whois.rotld.ro</name>
    <address>whois.rotld.ro</address>
    <tld>ro</tld>
    <tld>arts.ro</tld>
    <tld>co.ro</tld>
    <tld>com.ro</tld>
    <tld>firm.ro</tld>
    <tld>info.ro</tld>
    <tld>nom.ro</tld>
    <tld>nt.ro</tld>
    <tld>org.ro</tld>
    <tld>rec.ro</tld>
    <tld>ro.ro</tld>
    <tld>store.ro</tld>
    <tld>tm.ro</tld>
    <tld>www.ro</tld>
  </WhoisServerDefinition>
